### ISSUE TITLE
API broken

### ISSUE THREAD

**Issue by karthik** [ropensci/rfisheries#16]
Hi @andrewjdyck 
Did you change the API and remove the species end point? The package is now completely broken again.

**Comment by andrewjdyck** [comment]
I haven't made any change at all. Further, when I briefly checked the api (which is just links to json docs on github) the test passed. Can describe 'completely broken'

**Comment by andrewjdyck** [comment]
Shoot. Sorry, I was saying, can you give some more details on what you are seeing?

**Comment by karthik** [comment]
One of the two key bits of data that the API returns (species and landings), has disappeared.

```
http://www.openfisheries.org/api/landings/species/
```


```r
> url <- "http://openfisheries.org/api/landings/species"
> library(httr)
> GET(url)
Response [http://www.openfisheries.org/api/landings/species/]
  Date: 2015-02-15 15:55
  Status: 404
  Content-Type: text/html; charset=utf-8
  Size: 9.05 kB
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>Page not found &middot; GitHub Pages</title>
    <style type="text/css" media="screen">
      body {
        background-color: #f1f1f1;
        margin: 0;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
...
> 
```

**Comment by andrewjdyck** [comment]
Ah yes, o believe that we discussed this during the hotfix that was applied a few months back. The suffix '.json' mist now be applied to all api calls. I can do a better job of putting this in the documentation. Woukd this help?

**Comment by karthik** [comment]
yes please. and thanks @andrewjdyck

**Comment by andrewjdyck** [comment]
Sounds good. And thanks for tolerating the torrent of spelling errors above. Brutal!

**Comment by karthik** [comment]
Also my bad @andrewjdyck 
Many apologies.
I updated the package a while back, but accidentally installed from CRAN (without the `.json` suffix) and got these errors. Sorry again for hastily posting an issue without investigating further.
