### ISSUE TITLE
client error: (404) Not Found

### ISSUE THREAD

**Issue by matteodefelice** [ropensci/rfisheries#18]
I've just installed the package. 

> head( of_landings() )
Error in of_landings() : client error: (404) Not Found

> version
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          2.3                         
year           2015                        
month          12                          
day            10                          
svn rev        69752                       
language       R                           
version.string R version 3.2.3 (2015-12-10)
nickname       Wooden Christmas-Tree

**Comment by sckott** [comment]
made a change on a branch, try `devtools::install_github("ropensci/rfisheries@sckott-fix")`

**Comment by matteodefelice** [comment]
Tnx, it fixed the error.
